connect sys/QS_DATABASE_PASS@QS_PRIMARY_NAME as sysdba
set pages 1000 line 150
ALTER SYSTEM SET log_archive_dest_2  = '' SCOPE=BOTH;
ALTER SYSTEM SET DG_BROKER_CONFIG_FILE1 = '+DATA/guard.DAT' SCOPE=BOTH;
ALTER SYSTEM SET DG_BROKER_CONFIG_FILE2 = '+RECO/guard.DAT' SCOPE=BOTH;
ALTER SYSTEM SET DG_BROKER_START=TRUE;
connect sys/QS_DATABASE_PASS@QS_STANDBY_NAME as sysdba
set pages 1000 line 150
ALTER SYSTEM SET log_archive_dest_2  = '' SCOPE=BOTH;
ALTER SYSTEM SET DG_BROKER_CONFIG_FILE1 = '+DATA/guard.DAT' SCOPE=BOTH;
ALTER SYSTEM SET DG_BROKER_CONFIG_FILE2 = '+RECO/guard.DAT' SCOPE=BOTH;
ALTER SYSTEM SET DG_BROKER_START=TRUE;
exit
