connect target sys/QS_DATABASE_PASS@QS_PRIMARY_NAME
connect auxiliary sys/QS_DATABASE_PASS@QS_STANDBY_NAME

configure default device type to 'disk';
run {
allocate channel ch1 device type disk;
ALLOCATE AUXILIARY CHANNEL aux1 DEVICE TYPE DISK;
DUPLICATE TARGET DATABASE
  FOR STANDBY
  FROM ACTIVE DATABASE
  DORECOVER
  SPFILE
    SET db_unique_name='QS_STANDBY_NAME' COMMENT 'Is standby'
    SET LOG_ARCHIVE_DEST_2='SERVICE=QS_PRIMARY_NAME ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=QS_PRIMARY_NAME'
    SET FAL_SERVER='QS_PRIMARY_NAME' COMMENT 'Is primary'
  NOFILENAMECHECK;
release channel aux1;
release channel ch1;
}
